version: 2.0.{build}
install: 
  - ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex
branches:
  only:
  - master
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  account_feed: true
before_build:
- cmd: nuget restore
- ps: Vsix-IncrementVsixVersion
build:
  project: Sitecore.Rocks.sln
  verbosity: minimal
artifacts:
- path: src\Sitecore.Rocks.VisualStudio\bin\Release\Sitecore.Rocks.VisualStudio.vsix
  name: Sitecore.Rocks.VisualStudio.vsix